general:
  network-id: "<gradient:gold:yellow>ProxyTab Network</gradient>"
  update-interval-ms: 1000
  ignore-regex:
    - "^bot_.*"
  blacklisted-servers:
    - "minigames"
  default-server-name: "<gray>未知区域</gray>"

servers:
  group-order:
    - "lobby"
    - "survival"
    - "creative"
    - "minigames"
    - "default"
  mapping:
    lobby: "<light_purple>大厅</light_purple>"
    survival: "<blue>生存服</blue>"
    creative: "<green>创造服</green>"
    minigames: "<gold>小游戏</gold>"
tab:
  enabled: true
  header:
    enabled: true
    value: |
      <network_id>
  footer:
    enabled: true
    value: |
      <gray>服务器: <current_server></gray>  <gray>延迟: <ping> ms</gray>  <gray>在线玩家: <dark_green><server_online></dark_green>/<green><online></green></gray> 
  player-format: "<left:22><gray>[<player_server>] | </gray><white><player_name></white></left><right:5><gray>[<green><player_ping></green>]</gray></right>"
  sort-mode: "server_then_name"
  show-empty-group: false

announcements:
  chat:
    enabled: true
    format: |
      <dark_gray>+------------------------------+</dark_gray>
      <center:26><gold><bold>公告</bold></gold></center>
      <announcement>
      <close_button>
      <dark_gray>+------------------------------+</dark_gray>
    close-button:
      enabled: true
      format: "<click:run_command:'/proxytab close-notice'><hover:show_text:'点击后今日不再进行提醒'><gold>[今日不再提醒]</gold></hover></click>"
  tab:
    enabled: true
    format: |
      <dark_gray>+------------------------------+</dark_gray>
      <gold><bold>公告</bold></gold><newline><announcement>
      <dark_gray>+------------------------------+</dark_gray>

storage:
  type: "json"
  player-state-file: "data/player-state.json"
  announcements-file: "data/announcements.json"